LEARNER_PROFILE='''Adult learner in Poland preparing for TELC B1. Explain in English. Use Russian cognates/false-friend notes only when helpful.'''
def fill(template,**values):
    for k,v in values.items():template=template.replace(f'<<{k}>>',str(v))
    return template
CORE_SYSTEM=LEARNER_PROFILE+'''\nReturn JSON only for a Polish lesson: {"title_pl":"","title_en":"","reading_pl":"","reading_en":"","new_vocabulary":[{"polish":"","form_in_story":"","english":"","part_of_speech":"","why_important":"","example_pl":"","example_en":""}],"grammar_rules":[{"id":"","title":"","explanation":"","pattern":"","examples":[{"polish":"","english":""}],"story_examples":[""]}],"listening":{"type":"","situation_en":"","instruction_pl":"","lines":[{"speaker":"","text":""}],"tasks":[{"id":1,"question":"","options":["","",""],"correct_option":0}]}}. Reading: <<text_type>>, <<reading_min>>-<<reading_max>> words, level <<level>>. Exactly <<n_words>> vocabulary items: <<vocab_rule>>. Grammar exactly: <<grammar_list>>. Listening <<listening_type>>, <<listening_min>>-<<listening_max>> words, exactly <<n_listening>> tasks. Correct Polish. Every form_in_story occurs in reading.''' 
CORE_USER='''Day <<day>>, week <<week>>, <<phase>>, level <<level>>, theme <<theme>>, situation <<situation>>, type <<lesson_type>>. Known words: <<known_words>>'''
VOCAB_NEW='The <<n>> most important and difficult NEW useful words not already known.'
VOCAB_REVIEW='Review <<n>> words only from this week: <<week_words>>.'
PRACTICE_SYSTEM=LEARNER_PROFILE+'''\nReturn JSON only: {"exercises":[{"id":1,"section":"vocabulary","type":"choice","grammar_id":"","instruction_en":"","prompt":"","options":["","",""],"correct_option":0,"accepted_answers":[],"explanation_en":""}],"writing_tasks":[{"situation_pl":"","situation_en":"","points_pl":["","",""]}],"speaking":{"part":<<speaking_part>>,"title":"","instructions_pl":"","instructions_en":"","prompts":["","",""],"useful_phrases":[{"polish":"","english":""}],"opinions":[]},"quiz":[{"id":1,"type":"multiple_choice","question":"","options":["","","",""],"correct_option":0,"accepted_answers":[],"reference_answer":""}]}. Exactly <<n_ex_total>> exercises: <<n_ex_vocab>> vocabulary, <<n_ex_grammar>> grammar (<<per_rule>>), <<n_ex_le>> language_elements. Exactly 2 writing tasks, <<writing_focus>>, <<writing_min>>-<<writing_max>> words. Speaking: <<speaking_part_name>>. Quiz exactly <<n_quiz>>: <<n_mc>> multiple_choice, <<n_fill>> fill_blank, <<n_open>> open. CRITICAL: solve every choice task before setting correct_option; explanation_en must support the same option and every distractor must be wrong.''' 
PRACTICE_USER='''Level <<level>>, theme <<theme>>, situation <<situation>>. READING: <<reading>>. WORDS: <<words>>. GRAMMAR: <<grammar>>.'''
QUIZ_GRADER_SYSTEM='''Grade open Polish answers: 1 correct, .5 partly correct, 0 wrong. Never reveal model answer. JSON {"results":[{"id":1,"score":1,"feedback":""}]}'''
PRODUCTION_CRITERIA={'writing':['Task completion','Communicative design (structure, register, coherence)','Grammar accuracy','Vocabulary range'],'speaking':['Task completion','Fluency and coherence','Grammar accuracy','Vocabulary range']}
PRODUCTION_GRADER_SYSTEM='''Assess <<kind>> at CURRENT level <<level>>, not B1. Criteria: <<criteria>>. <<extra>> Return JSON {"criteria":[{"name":"","score":0,"comment":""}],"corrected_text":"","mistakes":[{"original":"","correction":"","explanation":""}],"feedback":""}.'''
SPEAKING_EXTRA='Transcript: ignore punctuation/capitalization and do not judge pronunciation.'
TUTOR_SYSTEM=LEARNER_PROFILE+'''\nTutor for day <<day>>, level <<level>>, theme <<theme>>. Never reveal quiz answers. Reading: <<reading>> Translation: <<translation>> Vocabulary: <<vocabulary>> Grammar: <<grammar>> Listening: <<listening>>'''
